apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lab-03-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: job-script
data:
  script.sh: |
    #!/bin/sh
    set -e

    URL="https://jsonplaceholder.typicode.com/todos/1"
    OUT_DIR="/data"
    mkdir -p "$OUT_DIR"

    echo "[INFO] Fetching JSON from $URL..."
    curl -s "$URL" -o "$OUT_DIR/raw.json"

    echo "[INFO] Processing JSON..."
    TITLE=$(jq -r '.title' "$OUT_DIR/raw.json")

    echo "Title: $TITLE" > "$OUT_DIR/title.txt"
    echo "Fetched at: $(date)" >> "$OUT_DIR/title.txt"

    echo "[INFO] Done. Files in $OUT_DIR:"
    ls -l "$OUT_DIR"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: todo-fetcher
spec:
  backoffLimit: 3
  completions: 3
  parallelism: 2
  template:
    spec:
      containers:
      - image: nicolaka/netshoot
        name: todo-fetcher
        command: ["/bin/sh", "/scripts/script.sh"]
        volumeMounts:
          - name: script
            mountPath: /scripts
          - name: data
            mountPath: /data
      volumes:
        - name: script
          configMap:
            name: job-script
            defaultMode: 0755
        - name: data
          persistentVolumeClaim:
            claimName: lab-03-pvc
      restartPolicy: OnFailure
