apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lab-03-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: job-script
data:
  script.sh: |
    #!/bin/sh
    set -e

    echo "[ERROR] Simulating failure..."
    exit 1
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: todos-fetcher-cron
spec:
  schedule: '*/5 * * * *'
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      name: todos-fetcher-cron
    spec:
      template:
        metadata:
          labels:
            app: todo-fetcher-cron
        spec:
          containers:
          - image: nicolaka/netshoot
            name: todos-fetcher-cron
            command: ["/bin/sh", "/scripts/script.sh"]
            volumeMounts:
              - name: script
                mountPath: /scripts
              - name: data
                mountPath: /data
          volumes:
            - name: script
              configMap:
                name: job-script
                defaultMode: 0755
            - name: data
              persistentVolumeClaim:
                claimName: lab-03-pvc
          restartPolicy: OnFailure
---
