apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespace-viewer-binding
  namespace: rbac-lab
subjects:
- kind: ServiceAccount
  name: viewer
  namespace: rbac-lab
roleRef:
  kind: Role
  name: namespace-viewer
  apiGroup: rbac.authorization.k8s.io
